# version: '3.8'

services:

  frontend:
    image: 'frontend'
    build: 'ft_transcendance/frontend'
    container_name: 'frontend'
    restart: 'always'
    volumes:
      - ./ft_transcendance/frontend:/app
    ports:
      - 8080:8080
    networks:
      - ft_transcendance
  django:
    build: 'ft_transcendance/pingpong'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"


networks:
  ft_transcendance:
    name: ft_transcendance
    driver_opts:
      type: bridge

volumes:
  postgres_data:
